path: /content/drive/MyDrive/object-tracking-data-set/whole-data/data
train: images/train # train images (relative to 'path') 1743042 images
val: images/val # val images (relative to 'path') 41620 images

# Classes
names:
  0: Car